include:
  - temporal.yaml

services:
  api:
    build:
      context: .
    env_file: docker.env
    environment:
      - SERVICE_TYPE=MAIN_BACKEND,DB_CONNECTOR,DB_SSH_CONNECTOR
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
      - code-executor
    restart: always

  jobs-runner:
    build:
      context: .
    env_file: docker.env
    environment:
      - SERVICE_TYPE=JOBS_RUNNER
    networks:
      - backend
    restart: always

  workflows-worker:
    build:
      context: .
    env_file: docker.env
    environment:
      - SERVICE_TYPE=WORKFLOW_TEMPORAL_WORKER
      - WORKFLOW_TEMPORAL_NAMESPACE=workflows
      - WORKFLOW_TASK_QUEUE=workflows
      - WORKFLOW_TEMPORAL_CLUSTER_FRONTEND_HOST=192.168.100.215
      - WORKFLOW_TEMPORAL_CLUSTER_FRONTEND_PORT=7233
      - NODE_OPTIONS=--max_old_space_size=1024
    networks:
      - backend
      - code-executor
    restart: always

  workflows-backend:
    build:
      context: .
    env_file: docker.env
    environment:
      - SERVICE_TYPE=WORKFLOW_BACKEND,DB_CONNECTOR,DB_SSH_CONNECTOR
      - WORKFLOW_TEMPORAL_NAMESPACE=workflows
      - WORKFLOW_TASK_QUEUE=workflows
      - WORKFLOW_TEMPORAL_CLUSTER_FRONTEND_HOST=192.168.100.215
      - WORKFLOW_TEMPORAL_CLUSTER_FRONTEND_PORT=7233
    networks:
      - backend
      - code-executor
    restart: always

  code-executor:
    build:
      context: .
      target: code-executor
    environment:
      - NODE_OPTIONS=--max_old_space_size=1024
    privileged: true
    networks:
      - code-executor
    restart: always

  https-portal:
    image: tryretool/https-portal:latest
    env_file: docker.env
    environment:
      STAGE: local
      CLIENT_MAX_BODY_SIZE: 40M
      KEEPALIVE_TIMEOUT: 605
      PROXY_CONNECT_TIMEOUT: 600
      PROXY_SEND_TIMEOUT: 600
      PROXY_READ_TIMEOUT: 600
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    restart: always

networks:
  frontend:
  backend:
  code-executor:

volumes:
  data:
  retooldb-data:
  data:
  retooldb-data:
